from setuptools import setup

setup(
    name='wordgame',
    version='',
    packages=['venv.Lib.site-packages.pip', 'venv.Lib.site-packages.pip._vendor',
              'venv.Lib.site-packages.pip._vendor.idna', 'venv.Lib.site-packages.pip._vendor.pep517',
              'venv.Lib.site-packages.pip._vendor.pytoml', 'venv.Lib.site-packages.pip._vendor.certifi',
              'venv.Lib.site-packages.pip._vendor.chardet', 'venv.Lib.site-packages.pip._vendor.chardet.cli',
              'venv.Lib.site-packages.pip._vendor.distlib', 'venv.Lib.site-packages.pip._vendor.distlib._backport',
              'venv.Lib.site-packages.pip._vendor.msgpack', 'venv.Lib.site-packages.pip._vendor.urllib3',
              'venv.Lib.site-packages.pip._vendor.urllib3.util', 'venv.Lib.site-packages.pip._vendor.urllib3.contrib',
              'venv.Lib.site-packages.pip._vendor.urllib3.contrib._securetransport',
              'venv.Lib.site-packages.pip._vendor.urllib3.packages',
              'venv.Lib.site-packages.pip._vendor.urllib3.packages.backports',
              'venv.Lib.site-packages.pip._vendor.urllib3.packages.ssl_match_hostname',
              'venv.Lib.site-packages.pip._vendor.colorama', 'venv.Lib.site-packages.pip._vendor.html5lib',
              'venv.Lib.site-packages.pip._vendor.html5lib._trie',
              'venv.Lib.site-packages.pip._vendor.html5lib.filters',
              'venv.Lib.site-packages.pip._vendor.html5lib.treewalkers',
              'venv.Lib.site-packages.pip._vendor.html5lib.treeadapters',
              'venv.Lib.site-packages.pip._vendor.html5lib.treebuilders', 'venv.Lib.site-packages.pip._vendor.lockfile',
              'venv.Lib.site-packages.pip._vendor.progress', 'venv.Lib.site-packages.pip._vendor.requests',
              'venv.Lib.site-packages.pip._vendor.packaging', 'venv.Lib.site-packages.pip._vendor.cachecontrol',
              'venv.Lib.site-packages.pip._vendor.cachecontrol.caches',
              'venv.Lib.site-packages.pip._vendor.webencodings', 'venv.Lib.site-packages.pip._vendor.pkg_resources',
              'venv.Lib.site-packages.pip._internal', 'venv.Lib.site-packages.pip._internal.cli',
              'venv.Lib.site-packages.pip._internal.req', 'venv.Lib.site-packages.pip._internal.vcs',
              'venv.Lib.site-packages.pip._internal.utils', 'venv.Lib.site-packages.pip._internal.models',
              'venv.Lib.site-packages.pip._internal.commands', 'venv.Lib.site-packages.pip._internal.operations',
              'venv.Lib.site-packages.nltk', 'venv.Lib.site-packages.nltk.lm', 'venv.Lib.site-packages.nltk.app',
              'venv.Lib.site-packages.nltk.ccg', 'venv.Lib.site-packages.nltk.sem', 'venv.Lib.site-packages.nltk.tag',
              'venv.Lib.site-packages.nltk.tbl', 'venv.Lib.site-packages.nltk.chat', 'venv.Lib.site-packages.nltk.draw',
              'venv.Lib.site-packages.nltk.misc', 'venv.Lib.site-packages.nltk.stem',
              'venv.Lib.site-packages.nltk.test', 'venv.Lib.site-packages.nltk.test.unit',
              'venv.Lib.site-packages.nltk.test.unit.lm', 'venv.Lib.site-packages.nltk.test.unit.translate',
              'venv.Lib.site-packages.nltk.chunk', 'venv.Lib.site-packages.nltk.parse',
              'venv.Lib.site-packages.nltk.corpus', 'venv.Lib.site-packages.nltk.corpus.reader',
              'venv.Lib.site-packages.nltk.cluster', 'venv.Lib.site-packages.nltk.metrics',
              'venv.Lib.site-packages.nltk.twitter', 'venv.Lib.site-packages.nltk.classify',
              'venv.Lib.site-packages.nltk.tokenize', 'venv.Lib.site-packages.nltk.inference',
              'venv.Lib.site-packages.nltk.sentiment', 'venv.Lib.site-packages.nltk.translate',
              'venv.Lib.site-packages.wheel', 'venv.Lib.site-packages.wheel.cli', 'venv.Lib.site-packages.wordnet',
              'venv.Lib.site-packages.wordnet.bin', 'venv.Lib.site-packages.wordnet.models',
              'venv.Lib.site-packages.colorama'],
    url='',
    license='',
    author='Rahat',
    author_email='',
    description=''
)
